
REGS.o: REGS.cpp REGS.h
	g++ REGS.cpp -c

ULA.o: ULA.cpp ULA.h
	g++ ULA.cpp -c

PC.o: PC.cpp PC.h
	g++ PC.cpp -c

MEM.o: MEM.cpp MEM.hpp
	g++ MEM.cpp -c

all: REGS.o ULA.o PC.o MEM.o


clear:
	rm *.o
